grasp_list:
  - biscuits:
        position:
          x: 0.56
          y: -0.24
          z: 0.97
        orientation:
          x: 0.5
          y: 0.5
          z: -0.5
          w: 0.5
    soap:
        position:
          x: 0.57
          y: -0.02
          z: 0.93
        orientation:
          x: -0.259
          y: 0.658
          z: 0.259
          w: 0.658
    soap2:
        position:
          x: 0.46
          y: 0.23
          z: 0.95
        orientation:
          x: 0.293
          y: 0.643
          z: -0.293
          w: 0.643
  - biscuits:
        position:
          x: 0.56
          y: -0.24
          z: 0.97
        orientation:
          x: 0.5
          y: 0.5
          z: -0.5
          w: 0.5
    soap:
        position:
          x: 0.57
          y: -0.02
          z: 0.93
        orientation:
          x: -0.259
          y: 0.658
          z: 0.259
          w: 0.658
    book:
        position:
          x: 0.59
          y: 0.28
          z: 0.86
        orientation:
          x: 0.140
          y: 0.693
          z: -0.140
          w: 0.693
    soap2:
       position:
         x: 0.46
         y: 0.23
         z: 0.95
       orientation:
         x: 0.293
         y: 0.643
         z: -0.293
         w: 0.643
    glue:
       position:
         x: 0.634
         y: 0.13
         z: 0.86
       orientation:
         x: 0.140
         y: 0.693
         z: -0.140
         w: 0.693
